DECLARE @A VARBINARY(8) = 0x0000000000000000;
DECLARE @B VARBINARY(8) = 0x0000000000000007;

DECLARE @P VARBINARY(8) = 0xFFFFFFFFFFFFFFC5;
DECLARE @N VARBINARY(8) = 0xFFFFFFFFFFFFFF43;

DECLARE @Gx VARBINARY(8) = 0x6B17D1F2E12C4247;
DECLARE @Gy VARBINARY(8) = 0x4FE342E2FE1A7F9B;

-- แปลงเป็น BIGINT
DECLARE @A_dec BIGINT = CAST(@A AS BIGINT);
DECLARE @B_dec BIGINT = CAST(@B AS BIGINT);
DECLARE @P_dec BIGINT = CAST(@P AS BIGINT);
DECLARE @N_dec BIGINT = CAST(@N AS BIGINT);
DECLARE @Gx_dec BIGINT = CAST(@Gx AS BIGINT);
DECLARE @Gy_dec BIGINT = CAST(@Gy AS BIGINT);

-- แสดงผลลัพธ์
SELECT
    @A_dec AS A_decimal,
    @B_dec AS B_decimal,
    @P_dec AS P_decimal,
    @N_dec AS N_decimal,
    @Gx_dec AS Gx_decimal,
    @Gy_dec AS Gy_decimal;
