services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sql@Min123
      - MSSQL_PID=Developer
    ports:
      - "14330:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

volumes:
  sql_data:
